Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocioRegistro.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/SOCIOSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using SocioRegistro.Models;

namespace SocioRegistro.Controllers
{
    public class SOCIOSController : Controller
    {
        private FINALWebEntities db = new FINALWebEntities();

        // GET: SOCIOS
        public ActionResult Index()
        {
            return View(db.SOCIOS.ToList());
        }

        // GET: SOCIOS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCIOS sOCIOS = db.SOCIOS.Find(id);
            if (sOCIOS == null)
            {
                return HttpNotFound();
            }
            return View(sOCIOS);
        }

        // GET: SOCIOS/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SOCIOS/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NOMBRE,APELLIDO,CEDULA,FOTO,DIRECCION,NUMERO_CONTACTO,SEXO,EDAD,FECHA_NACIMIENTO,FAMILIARES,TIPO_MEMBRESIA,LUGAR_TRABAJO,DIRECCION_OFICINA,TEL_OFICINA,ESTADO_MENBRESIA,FECHA_INGRESO,FECHA_SALIDA")] SOCIOS sOCIOS)
        {

            HttpPostedFileBase FileBase = Request.Files[0];

            WebImage foto = new WebImage(FileBase.InputStream);

            sOCIOS.FOTO = foto.GetBytes();

            if (ModelState.IsValid)
            {
                db.SOCIOS.Add(sOCIOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sOCIOS);
        }

        // GET: SOCIOS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCIOS sOCIOS = db.SOCIOS.Find(id);
            if (sOCIOS == null)
            {
                return HttpNotFound();
            }
            return View(sOCIOS);
        }

        // POST: SOCIOS/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NOMBRE,APELLIDO,CEDULA,FOTO,DIRECCION,NUMERO_CONTACTO,SEXO,EDAD,FECHA_NACIMIENTO,FAMILIARES,TIPO_MEMBRESIA,LUGAR_TRABAJO,DIRECCION_OFICINA,TEL_OFICINA,ESTADO_MENBRESIA,FECHA_INGRESO,FECHA_SALIDA")] SOCIOS sOCIOS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sOCIOS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sOCIOS);
        }

        // GET: SOCIOS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCIOS sOCIOS = db.SOCIOS.Find(id);
            if (sOCIOS == null)
            {
                return HttpNotFound();
            }
            return View(sOCIOS);
        }

        // POST: SOCIOS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SOCIOS sOCIOS = db.SOCIOS.Find(id);
            db.SOCIOS.Remove(sOCIOS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult getImage(int id)
        {
            SOCIOS fotok = db.SOCIOS.Find(id);
            byte[] byteImage = fotok.FOTO;
            
            MemoryStream memoryStream = new MemoryStream(byteImage);
            Image image = Image.FromStream(memoryStream);

            memoryStream = new MemoryStream();
            image.Save(memoryStream, ImageFormat.Jpeg);
            memoryStream.Position = 0;

            return File(memoryStream, "image/jpg");

        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>*@

<div class="row">
    <div class="col-md-4">
        <h2>@Html.ActionLink("Usuario", "Index", "SOCIOS")</h2>
        @*<p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>*@
    </div>
    @*<div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>*@
</div>